### ISSUE TITLE
wc: data/tac2017/vocab.new: No such file or directory

### ISSUE THREAD

**Issue by SeekPoint** [se4u/nvse#1]
```
mldl@ub1604:~/ub16_prj/nvse$ make train
wc: data/tac2017/vocab.new: No such file or directory
Makefile:27: *** missing separator.  Stop.
mldl@ub1604:~/ub16_prj/nvse$
```

**Comment by se4u** [comment]
Did you solve this issue ?

**Comment by SeekPoint** [comment]
just tell me where to get the dataset

**Comment by se4u** [comment]
I sent an email with the link for the data to yk_data@126.com. Please close the issue once you have downloaded the data. thanks.

**Comment by SeekPoint** [comment]
just double checked, not see your email.
would see any feedback of email?

**Comment by se4u** [comment]
Did you check your spam folder. The data is stored on microsoft onedrive.

**Comment by SeekPoint** [comment]
yes, got it.

thanks!
